## 7. Python Fundamentals for Data Engineering
This section covers the foundational Python concepts essential for data engineering tasks. Understanding these basics is crucial for building robust data pipelines and processing data efficiently.

### Core Concepts

#### Variables and Data Types
In data engineering, you constantly deal with various types of data. Python's dynamic typing and built-in data types make it flexible for handling this. Variables are used to store data values.

**Practicals:**
*   **Integers (`int`):** Used for counts, IDs, e.g., `transaction_id = 100123`
*   **Floating-point numbers (`float`):** Used for financial values, calculations, e.g., `sale_amount = 199.99`
*   **Strings (`str`):** Used for text data, product names, customer names, e.g., `product_name = "Smart Speaker Pro"`
*   **Booleans (`bool`):** Used for flags, conditions, e.g., `is_promo_applied = True`

```python
# Example: Variables and Data Types for Sales Data
total_transactions = 25000
avg_daily_revenue = 15000.75
campaign_status = "Active"
is_holiday_season = True

print(f"Total Transactions: {total_transactions}, Type: {type(total_transactions)}")
print(f"Average Daily Revenue: {avg_daily_revenue}, Type: {type(avg_daily_revenue)}")
print(f"Campaign Status: {campaign_status}, Type: {type(campaign_status)}")
print(f"Is Holiday Season: {is_holiday_season}, Type: {type(is_holiday_season)}")
```

#### Lists, Dictionaries, and Sets
These are fundamental data structures for organizing collections of data. Choosing the right one depends on your data's nature and the operations you need to perform.

*   **Lists (`list`):** Ordered, mutable collections of items. Ideal for sequences of records or items where order matters.
    **Practical Use:** Storing a sequence of daily sales figures, a list of product IDs in an order, or rows from a sales CSV.

*   **Dictionaries (`dict`):** Unordered, mutable collections of key-value pairs. Ideal for structured records where you access data by a unique identifier (key).
    **Practical Use:** Representing a single order record (e.g., a JSON order object), product metadata, or mapping product IDs to prices.

*   **Sets (`set`):** Unordered, mutable collections of *unique* items. Useful for quickly checking membership or removing duplicates.
    **Practical Use:** Storing unique customer IDs, distinct product categories, or performing set operations (union, intersection) on sales data.

```python
# Example: Lists, Dictionaries, Sets for Sales Data

# List of daily sales amounts
daily_sales_amounts = [1250.75, 1300.20, 1180.50, 1450.00, 1320.90]
print(f"Daily Sales Amounts (List): {daily_sales_amounts}")
print(f"First day's sales: {daily_sales_amounts[0]}")
daily_sales_amounts.append(1510.30) # Add a new day's sales
print(f"Updated sales amounts: {daily_sales_amounts}\n")

# Dictionary representing a product record
product_details = {
    "product_id": "P876",
    "product_name": "Wireless Headphones",
    "price": 79.99,
    "stock_level": 500
}
print(f"Product Details (Dictionary): {product_details}")
print(f"Product Name: {product_details['product_name']}")
product_details['stock_level'] = 490 # Update stock level
print(f"Updated Stock Level: {product_details['stock_level']}\n")

# Set of unique product categories
product_categories = {"Electronics", "Apparel", "Home Goods", "Apparel", "Books"}
print(f"Unique Product Categories (Set): {product_categories}")
product_categories.add("Outdoor") # Add a new unique category
print(f"After adding 'Outdoor': {product_categories}")
print(f"Is 'Electronics' a category? {'Electronics' in product_categories}\n")
```

#### Functions
Functions are reusable blocks of code that perform specific tasks. They promote modularity, readability, and reduce code duplication, which are vital in large data pipelines.

**Practical Use:** Encapsulating data cleaning steps for product names, transformation logic for calculating commissions, or validation routines for order quantities.

```python
# Example: Function for basic product name cleaning
def clean_product_name(name):
    if isinstance(name, str):
        return name.strip().lower()
    return None # Handle non-string input gracefully

raw_product_title = "  New Smartwatch Xtreme Edition  \n"
cleaned_title = clean_product_name(raw_product_title)
print(f"Original: '{raw_product_title}'")
print(f"Cleaned: '{cleaned_title}'\n")

# Function for simple sales aggregation
def calculate_average_sale(transaction_amounts):
    if not transaction_amounts:
        return 0
    return sum(transaction_amounts) / len(transaction_amounts)

transaction_values = [50.00, 120.50, 30.75, 200.00, 85.25]
avg_sale = calculate_average_sale(transaction_values)
print(f"Transaction Values: {transaction_values}")
print(f"Average Sale Value: {avg_sale:.2f}")
```

#### Loops and Conditionals
These control the flow of execution in your code, allowing for repetitive tasks and decision-making—essential for processing sales records, iterating through product catalogs, or applying business rules like discounts.

*   **`for` loop:** Iterates over a sequence (list of orders, product catalog, etc.).
*   **`while` loop:** Repeats a block of code as long as a condition is true (e.g., processing records until a file's end).
*   **`if`/`elif`/`else`:** Executes different code blocks based on conditions (e.g., applying different tax rates based on region, or discounts based on order value).

**Practical Use:** Iterating through order items to calculate total cost, validating sales records for missing values, or flagging high-value transactions.

```python
# Example: Loops and Conditionals for sales transaction processing

def analyze_transaction_data(transactions):
    high_value_transactions = []
    for tx in transactions:
        # Check if the transaction is valid (has amount and is positive)
        if isinstance(tx.get('amount'), (int, float)) and tx['amount'] > 0:
            # Apply business logic: flag transactions over a certain threshold
            if tx['amount'] > 100: # Threshold for high-value transaction
                tx['status'] = 'High Value'
                high_value_transactions.append(tx)
            else:
                tx['status'] = 'Standard'
        else:
            tx['status'] = 'Invalid Data'
            print(f"Warning: Invalid transaction data encountered: {tx}")
    return high_value_transactions

sales_transactions = [
    {'id': 'T001', 'amount': 75.50, 'product': 'Book'},
    {'id': 'T002', 'amount': 150.25, 'product': 'Laptop'},
    {'id': 'T003', 'amount': 99.00, 'product': 'Mouse'},
    {'id': 'T004', 'amount': 220.00, 'product': 'Monitor'},
    {'id': 'T005', 'amount': -10.00, 'product': 'Refund'},
    {'id': 'T006', 'amount': None, 'product': 'Unknown'}
]

print("Processing sales transactions:")
flagged_transactions = analyze_transaction_data(sales_transactions)
for tx in sales_transactions:
    print(f"Transaction {tx['id']}: Amount=${tx.get('amount', 'N/A')}, Status: {tx['status']}")

print("\nHigh-value transactions flagged:")
for hvt in flagged_transactions:
    print(hvt)
```

### Quiz Time!
1. Which of the following is NOT a core concept in Python for Data Engineering?
   a) Variables and data types
   b) SQL queries
   c) Functions
   d) Loops and conditionals
   *Answer: b)*

## 8. Writing Modular and Testable Code
Good software engineering practices are vital in data engineering to ensure maintainable, scalable, and reliable data systems. This section highlights key practices for writing clean code.

### Best Practices

#### Break code into small functions
Each function should ideally do one thing and do it well. This makes code easier to understand, debug, and reuse. In data engineering, this means breaking down complex ETL (Extract, Transform, Load) steps into granular functions.

**Practical Use:** Instead of one large function for 'process_sales_data', you might have `extract_sales_records`, `clean_sales_data`, `transform_sales_dimensions`, `load_sales_to_warehouse`.

#### Use clear naming conventions
Descriptive names for variables, functions, and classes significantly improve code readability for yourself and others. Avoid abbreviations that are not universally understood.

**Practical Use:** Instead of `df`, use `sales_dataframe`. Instead of `xform`, use `transform_customer_data`.

#### Avoid hardcoding values
Configuration settings, file paths, database credentials, or threshold values should not be embedded directly in the code. Use configuration files, environment variables, or function parameters. This makes your code more flexible and easier to deploy across different environments (dev, test, prod).

**Practical Use:** Storing database connection strings in environment variables, or loading a JSON config file for data transformation rules.

#### Write unit tests
Unit tests verify that individual components (functions, classes) of your code work as expected in isolation. They catch bugs early, provide documentation for how a component should work, and facilitate safe refactoring.

**Practical Use:** Testing a data cleaning function to ensure it handles edge cases (e.g., null values, incorrect types) correctly.

### Example
Here’s an example demonstrating how to break down a data transformation task into smaller, testable functions, along with a simple unit test.

```python
import unittest

def clean_product_string(value):
    """Cleans a string (e.g., product name, category) by stripping whitespace and converting to lowercase."""
    if isinstance(value, str):
        return value.strip().lower()
    return value # Return as is if not a string (or handle error as needed)

def parse_quantity_sold(qty_str):
    """Parses a quantity string to an integer, handling potential errors."""
    try:
        return int(qty_str)
    except (ValueError, TypeError):
        return None # Indicate parsing failure

def transform_order_item_record(record):
    """Applies cleaning and parsing to a single order item record dictionary."""
    transformed_record = {}
    transformed_record['product_name'] = clean_product_string(record.get('product_name'))
    transformed_record['category'] = clean_product_string(record.get('category'))
    transformed_record['quantity_sold'] = parse_quantity_sold(record.get('quantity'))
    transformed_record['unit_price'] = record.get('unit_price') # Assume price is already numeric
    return transformed_record

# --- Demonstration ---
raw_order_data = [
    {"product_name": "  Laptop Pro  ", "category": "ELECTRONICS", "quantity": "1", "unit_price": 1200.00},
    {"product_name": "Gaming Mouse", "category": "electronics ", "quantity": "two", "unit_price": 50.00},
    {"product_name": "Desk Lamp", "category": None, "quantity": 1, "unit_price": 25.50} # quantity already int
]

print("Original Order Data:")
for record in raw_order_data:
    print(record)

print("\nTransformed Order Data:")
processed_order_data = [transform_order_item_record(record) for record in raw_order_data]
for record in processed_order_data:
    print(record)

# --- Unit Test Example ---
class TestSalesDataTransformation(unittest.TestCase):

    def test_clean_product_string(self):
        self.assertEqual(clean_product_string("  SMART TV "), "smart tv")
        self.assertEqual(clean_product_string("Home Theater"), "home theater")
        self.assertIsNone(clean_product_string(None))
        self.assertEqual(clean_product_string(123), 123) # Non-string passed through

    def test_parse_quantity_sold(self):
        self.assertEqual(parse_quantity_sold("10"), 10)
        self.assertIsNone(parse_quantity_sold("five"))
        self.assertIsNone(parse_quantity_sold(None))
        self.assertEqual(parse_quantity_sold(3), 3) # Already an int

    def test_transform_order_item_record(self):
        raw_record = {"product_name": "  Earbuds ", "category": "AUDIO", "quantity": "2", "unit_price": 79.99}
        expected_transformed = {"product_name": "earbuds", "category": "audio", "quantity_sold": 2, "unit_price": 79.99}
        self.assertEqual(transform_order_item_record(raw_record), expected_transformed)

        raw_record_invalid = {"product_name": "Book", "category": None, "quantity": "one", "unit_price": 15.00}
        expected_transformed_invalid = {"product_name": "book", "category": None, "quantity_sold": None, "unit_price": 15.00}
        self.assertEqual(transform_order_item_record(raw_record_invalid), expected_transformed_invalid)

print("\nRunning Unit Tests...")
# To run tests in a notebook, you can use TextTestRunner
loader = unittest.TestLoader()
suite = loader.loadTestsFromTestCase(TestSalesDataTransformation)
runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite)
```
**Explanation:**
*   `clean_product_string` and `parse_quantity_sold` are small, focused functions, each doing one job related to sales data.
*   `transform_order_item_record` composes these smaller functions to process a single order item record, demonstrating modularity.
*   The `TestSalesDataTransformation` class contains unit tests for each function, ensuring they work as expected under different inputs relevant to sales data.

## 9. Working with File Formats
Data engineers frequently work with various file formats. This section covers common formats and how to interact with them using Python. We'll provide practical, runnable examples for each.

### CSV (Comma-Separated Values)
CSV is a common plain-text format for tabular data. It's simple, human-readable, and widely supported. Python's built-in `csv` module is highly effective for reading and writing CSV files, and `pandas` provides even more powerful tools.

**Practical Use:** Exporting sales reports from CRM systems, simple data exchange of product catalogs, small to medium datasets of customer orders.

```python
import csv
import pandas as pd

# --- Create a dummy CSV file for product sales ---
data_to_write = [
    ['product_id', 'product_name', 'category', 'price', 'units_sold'],
    ['P001', 'Laptop', 'Electronics', 1200.50, 5],
    ['P002', 'Gaming Mouse', 'Electronics', 25.00, 15],
    ['P003', 'Mechanical Keyboard', 'Electronics', 75.25, 8]
]

csv_file_path = 'sales_products.csv'

with open(csv_file_path, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(data_to_write)
print(f"Created '{csv_file_path}' with content:\n")
with open(csv_file_path, 'r') as f:
    print(f.read())

# --- Read the CSV file using csv module ---
print("\nReading CSV with csv.reader (product sales data):")
with open(csv_file_path, 'r') as f:
    reader = csv.reader(f)
    header = next(reader) # Read header row
    print(f"Header: {header}")
    for row in reader:
        print(f"Row: {row}")

# --- Read the CSV file into a Pandas DataFrame ---
print("\nReading CSV into Pandas DataFrame (product sales data):")
df_csv = pd.read_csv(csv_file_path)
display(df_csv)
```

### JSON (JavaScript Object Notation)
JSON is a lightweight data-interchange format. It's human-readable and easy for machines to parse. Often used for data transmission between a server and web application, or for configuration files. Python's `json` module allows easy serialization (Python objects to JSON string) and deserialization (JSON string to Python objects) of JSON data.

**Practical Use:** Web API responses for order details, storing complex customer profiles, logging structured sales events, NoSQL databases storing flexible sales records.

```python
import json

# --- Sales order data to be written to JSON ---
json_data_to_write = [
    {
        "order_id": "ORD001",
        "customer_id": "C101",
        "order_date": "2023-10-27",
        "items": [
            {"product_id": "P001", "product_name": "Laptop", "qty": 1, "price": 1200.50},
            {"product_id": "P002", "product_name": "Mouse", "qty": 1, "price": 25.00}
        ],
        "total_amount": 1225.50
    },
    {
        "order_id": "ORD002",
        "customer_id": "C102",
        "order_date": "2023-10-27",
        "items": [
            {"product_id": "P003", "product_name": "Keyboard", "qty": 2, "price": 75.25}
        ],
        "total_amount": 150.50
    }
]

json_file_path = 'sales_orders.json'

# --- Write JSON sales order data to a file ---
with open(json_file_path, 'w') as f:
    json.dump(json_data_to_write, f, indent=4)
print(f"Created '{json_file_path}' with content:\n")
with open(json_file_path, 'r') as f:
    print(f.read())

# --- Read JSON sales order data from a file ---
print("\nReading JSON from file (sales orders):")
with open(json_file_path, 'r') as f:
    loaded_json_data = json.load(f)
display(loaded_json_data)

# Accessing elements
print(f"\nFirst order ID: {loaded_json_data[0]['order_id']}")
print(f"Second order total amount: {loaded_json_data[1]['total_amount']}")
```


### Quiz Time!
1. Which Python library is commonly used for working with Parquet files?
   a) `csv`
   b) `json`
   c) `pandas` (with `pyarrow` or `fastparquet`)
   d) `fastavro`
   *Answer: c)*

2. If you need to read an Avro file, which library would you typically use?
   a) `pandas`
   b) `fastavro`
   c) `openpyxl`
   d) `sqlalchemy`
   *Answer: b)*

## 10. Error Handling and Logging
Robust data engineering pipelines require proper error handling and logging to ensure reliability, traceability, and facilitate debugging. This section introduces essential techniques with practical examples.

### Error Handling (`try-except-finally`)
Using `try-except` blocks allows your program to gracefully handle runtime errors, preventing crashes and providing informative feedback. `finally` blocks ensure cleanup code runs regardless of whether an exception occurred.

**Key Concepts:**
*   **`try`:** The code block where an exception might occur.
*   **`except`:** Catches and handles specific exceptions.
*   **`else`:** (Optional) Code to run if the `try` block completes without an exception.
*   **`finally`:** (Optional) Code to run no matter what happens (e.g., closing resources).

**Practical Use (Sales Data Scenario):**
*   Handling `FileNotFoundError` when trying to load a daily sales CSV.
*   Handling `ValueError` during type conversions for `quantity` or `price` fields in sales records.
*   Handling `KeyError` when accessing a `customer_id` that might not exist in a lookup table.
*   Ensuring file handles for sales reports or database connections to the sales database are closed.

```python
# Example: Error Handling with sales metric calculation

def calculate_average_sale_per_item(total_revenue, total_items_sold):
    try:
        # Ensure we don't divide by zero if no items were sold
        if total_items_sold == 0:
            raise ZeroDivisionError("Total items sold cannot be zero.")
        result = total_revenue / total_items_sold
    except ZeroDivisionError as e:
        print(f"Error calculating average: {e}")
        return None
    except TypeError:
        print("Error: Both total revenue and total items sold must be numbers.")
        return None
    else:
        print(f"Average sale per item: ${total_revenue:.2f} / {total_items_sold} = ${result:.2f}")
        return result
    finally:
        print("--- Average sale calculation attempt complete ---\n")

calculate_average_sale_per_item(1000.00, 50)      # Successful calculation
calculate_average_sale_per_item(500.00, 0)        # ZeroDivisionError
calculate_average_sale_per_item(250.00, "10")     # TypeError

# Example: Handling sales configuration file operations with try-except-finally
def read_sales_config(filename):
    file_handle = None
    try:
        file_handle = open(filename, 'r')
        content = file_handle.read()
        print(f"Content of sales config '{filename}':\n{content}")
        return content
    except FileNotFoundError:
        print(f"Error: Sales configuration file '{filename}' not found.")
    except IOError as e:
        print(f"Error reading sales config file '{filename}': {e}")
    finally:
        if file_handle:
            file_handle.close()
            print(f"Closed file handle for sales config '{filename}'.")

# Create a dummy sales config file
with open('sales_pipeline_config.txt', 'w') as f:
    f.write("DAILY_SALES_THRESHOLD=10000\nANOMALY_REPORT_EMAIL=data_team@example.com")

read_sales_config('sales_pipeline_config.txt')
print("\n")
read_sales_config('non_existent_sales_config.txt')
```

### Logging (`logging` module)
Logging is crucial for tracking the execution flow of your applications, diagnosing issues, and monitoring system health without interrupting program execution. Python's `logging` module is powerful and flexible, allowing you to direct messages to the console, files, or even network services.

**Logging Levels (in increasing order of severity):**
*   **`DEBUG`:** Detailed information, typically only of interest when diagnosing problems.
*   **`INFO`:** Confirmation that things are working as expected.
*   **`WARNING`:** An indication that something unexpected happened, or indicative of some problem in the near future (e.g., ‘disk space low’). The software is still working as expected.
*   **`ERROR`:** Due to a more serious problem, the software has not been able to perform some function.
*   **`CRITICAL`:** A serious error, indicating that the program itself may be unable to continue running.

**Practical Use (Sales Data Scenario):**
*   **`INFO`:** Start/end of daily sales processing, successful loading of sales data from an S3 bucket, completion of a sales report generation.
*   **`WARNING`:** Data quality issues (e.g., missing `product_id` in some sales records, which are handled by imputation), sales figures slightly below expected thresholds.
*   **`ERROR`:** Failed connection to the sales database, unhandled exceptions in a sales aggregation step, inability to write a processed sales file.
*   **`CRITICAL`:** Sales pipeline halted due to a critical dependency failure, leading to loss of real-time sales insights.

```python
import logging
import sys # For logging to stderr

# --- Basic Logging Configuration (to console for sales pipeline) ---
# Configure basic logging to output to console with INFO level and above
# A more robust configuration would use Handlers and Formatters
logging.basicConfig(
    level=logging.INFO, # Set default level for messages
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout) # Log to standard output
    ]
)

print("\n--- Sales Console Logging Example ---")
logging.debug("Debugging sales data parsing for a specific record.") # This message will not be shown
logging.info("Daily sales pipeline started successfully.")
logging.warning("Some sales records had invalid timestamps, using current time as default.")
logging.error("Failed to connect to the sales analytics database. Retrying in 5 minutes...")
logging.critical("Sales data warehouse ETL terminated due to unrecoverable storage error.")


# --- Logging Sales Events to a File Example ---
file_logger = logging.getLogger('sales_file_logger')
file_logger.setLevel(logging.DEBUG) # Log all messages related to sales events to file

file_handler = logging.FileHandler('sales_pipeline.log')
file_handler.setLevel(logging.DEBUG)
file_formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
file_handler.setFormatter(file_formatter)
file_logger.addHandler(file_handler)

print("\n--- Sales File Logging Example (check sales_pipeline.log) ---")
file_logger.debug("Detailed debugging for sales data transformation step.")
file_logger.info("Processed 5000 sales transactions from external API.")
file_logger.error("Sales volume anomaly detected for region 'West'. Investigation required.")

# Verify log file content (after execution, you can view 'sales_pipeline.log')
print("\nContent of sales_pipeline.log (if created):\n")
try:
    with open('sales_pipeline.log', 'r') as f:
        print(f.read())
except FileNotFoundError:
    print("sales_pipeline.log not yet created or found.")

```
**Explanation:**
*   `logging.basicConfig` sets up a default logger. We've configured it to print `INFO` and higher-level messages to `stdout` with a timestamp and level.
*   We demonstrate different logging levels in action within a sales context.
*   For file logging, we create a specific logger (`sales_file_logger`), set its level, and add a `FileHandler` to direct messages to `sales_pipeline.log`.
*   This separation allows different logging destinations and verbosity levels for different parts of your sales data application.

### Quiz Time!
1. What keyword is used to handle potential errors in Python?
   a) `catch`
   b) `handle`
   c) `try`
   d) `error`
   *Answer: c)*

2. Which `logging` level is typically used to confirm that things are working as expected?
   a) INFO
   b) WARNING
   c) ERROR
   d) DEBUG
   *Answer: a)*

## 11. Summary
By the end of this lesson, students should:
*   Understand key data roles and systems
*   Know how data flows through a lifecycle
*   Be comfortable with Python basics for data engineering
*   Handle different common data formats (CSV, JSON, Parquet, Avro)
*   Write clean, modular, and reliable code using best practices, error handling, and logging.

This summary reiterates the key learning objectives covered throughout the entire lesson program, emphasizing the comprehensive skills gained in Python for Data Engineering.

## 12. Suggested Exercises
Here's a suggested exercise to apply the concepts learned in this tutorial:

### Exercise: Read CSV, Filter, Transform, and Write to JSON
**Task:** Write Python code that reads data from a CSV file, filters it based on a condition, transforms one of its fields, and then writes the processed data to a JSON file.

**Steps:**
1.  Create a dummy CSV file named `sales_data.csv` with columns like `product_name`, `category`, `price`, `quantity`, `region`. Include some rows where `category` is 'Electronics' and some where `region` is 'West'.
2.  Read the content of `sales_data.csv` into a Pandas DataFrame.
3.  Filter the DataFrame to include only sales where the `category` is 'Electronics' AND the `quantity` is greater than 1.
4.  Add a new column `total_sale` calculated as `price * quantity`.
5.  Convert the filtered and transformed DataFrame into a list of dictionaries.
6.  Write this list of dictionaries to a new JSON file named `electronics_sales.json`.

**Hint:** You'll use `pandas` for reading/filtering/transforming and the `json` module for writing, combining skills from sections 7 and 9.

In [7]:
# --- Solution for Exercise: Read CSV, Filter, Transform, and Write to JSON ---

import pandas as pd
import json
import csv

# 1. Create a dummy CSV file named `sales_data.csv`
sales_data_to_write = [
    ['product_name', 'category', 'price', 'quantity', 'region'],
    ['Laptop', 'Electronics', 1200.50, 1, 'East'],
    ['Mouse', 'Electronics', 25.00, 3, 'West'],
    ['Keyboard', 'Electronics', 75.25, 2, 'North'],
    ['Desk Chair', 'Furniture', 150.00, 1, 'West'],
    ['Monitor', 'Electronics', 300.00, 1, 'South'],
    ['Webcam', 'Electronics', 40.00, 5, 'East'],
    ['Coffee Table', 'Furniture', 80.00, 2, 'North']
]

csv_sales_file = 'sales_data.csv'
with open(csv_sales_file, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(sales_data_to_write)

print(f"Created '{csv_sales_file}'. Content:\n")
with open(csv_sales_file, 'r') as f:
    print(f.read())

# 2. Read the content of `sales_data.csv` into a Pandas DataFrame.
df_sales = pd.read_csv(csv_sales_file)
print("\nOriginal DataFrame:")
display(df_sales)

# 3. Filter the DataFrame to include only sales where the `category` is 'Electronics' AND the `quantity` is greater than 1.
df_filtered = df_sales[(df_sales['category'] == 'Electronics') & (df_sales['quantity'] > 1)]
print("\nFiltered DataFrame (Electronics & quantity > 1):")
display(df_filtered)

# 4. Add a new column `total_sale` calculated as `price * quantity`.
df_filtered['total_sale'] = df_filtered['price'] * df_filtered['quantity']
print("\nDataFrame with 'total_sale' column:")
display(df_filtered)

# 5. Convert the filtered and transformed DataFrame into a list of dictionaries.
# Use .to_dict(orient='records') for a list of dictionaries
json_output_list = df_filtered.to_dict(orient='records')
print("\nConverted to List of Dictionaries:")
display(json_output_list)

# 6. Write this list of dictionaries to a new JSON file named `electronics_sales.json`.
json_output_file = 'electronics_sales.json'
with open(json_output_file, 'w') as f:
    json.dump(json_output_list, f, indent=4)

print(f"\nCreated '{json_output_file}'. Content:\n")
with open(json_output_file, 'r') as f:
    print(f.read())

Created 'sales_data.csv'. Content:

product_name,category,price,quantity,region
Laptop,Electronics,1200.5,1,East
Mouse,Electronics,25.0,3,West
Keyboard,Electronics,75.25,2,North
Desk Chair,Furniture,150.0,1,West
Monitor,Electronics,300.0,1,South
Webcam,Electronics,40.0,5,East
Coffee Table,Furniture,80.0,2,North


Original DataFrame:

   product_name     category    price  quantity region
0        Laptop  Electronics  1200.50         1   East
1         Mouse  Electronics    25.00         3   West
2      Keyboard  Electronics    75.25         2  North
3    Desk Chair    Furniture   150.00         1   West
4       Monitor  Electronics   300.00         1  South
5        Webcam  Electronics    40.00         5   East
6  Coffee Table    Furniture    80.00         2  North

Filtered DataFrame (Electronics & quantity > 1):

  product_name     category  price  quantity region
1        Mouse  Electronics  25.00         3   West
2     Keyboard  Electronics  75.25         2  North
5       Webcam  Electronics  40.00         5   East

DataFrame with 'total_sale' column:

/tmp/ipykernel_752/3295211889.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['total_sale'] = df_filtered['price'] * df_filtered['quantity']

  product_name     category  price  quantity region  total_sale
1        Mouse  Electronics  25.00         3   West        75.0
2     Keyboard  Electronics  75.25         2  North       150.5
5       Webcam  Electronics  40.00         5   East       200.0

Converted to List of Dictionaries:

[{'product_name': 'Mouse',
  'category': 'Electronics',
  'price': 25.0,
  'quantity': 3,
  'region': 'West',
  'total_sale': 75.0},
 {'product_name': 'Keyboard',
  'category': 'Electronics',
  'price': 75.25,
  'quantity': 2,
  'region': 'North',
  'total_sale': 150.5},
 {'product_name': 'Webcam',
  'category': 'Electronics',
  'price': 40.0,
  'quantity': 5,
  'region': 'East',
  'total_sale': 200.0}]

Created 'electronics_sales.json'. Content:

[
    {
        "product_name": "Mouse",
        "category": "Electronics",
        "price": 25.0,
        "quantity": 3,
        "region": "West",
        "total_sale": 75.0
    },
    {
        "product_name": "Keyboard",
        "category": "Electronics",
        "price": 75.25,
        "quantity": 2,
        "region": "North",
        "total_sale": 150.5
    },
    {
        "product_name": "Webcam",
        "category": "Electronics",
        "price": 40.0,
        "quantity": 5,
        "region": "East",
        "total_sale": 200.0
    }
]

## 7. Python Fundamentals for Data Engineering
This section covers the foundational Python concepts essential for data engineering tasks. Understanding these basics is crucial for building robust data pipelines and processing data efficiently.

### Core Concepts
*   **Variables and data types:** How to store and manipulate different kinds of data (integers, strings, lists, dictionaries, etc.).
*   **Lists, dictionaries, sets:** Understanding these fundamental data structures for organizing collections of data.
*   **Functions:** Writing reusable blocks of code to perform specific tasks, promoting modularity and readability.
*   **Loops and conditionals:** Controlling the flow of execution, allowing for repetitive tasks and decision-making in your code.

### Example
Here's a simple Python function that demonstrates loops and conditionals to process a list of numbers:
```python
def process_data(data):
    return [x * 2 for x in data if x > 0]
```
**Explanation:** This function takes a list of `data`, filters out non-positive numbers (`if x > 0`), and then doubles the remaining positive numbers (`x * 2`), returning a new list.

### Quiz Time!
1. Which of the following is NOT a core concept in Python for Data Engineering?
   a) Variables and data types
   b) SQL queries
   c) Functions
   d) Loops and conditionals
   *Answer: b)*

## 8. Writing Modular and Testable Code
Good software engineering practices are vital in data engineering to ensure maintainable, scalable, and reliable data systems. This section highlights key practices for writing clean code.

### Best Practices
*   **Break code into small functions:** Each function should ideally do one thing and do it well, making code easier to understand, debug, and reuse.
*   **Use clear naming conventions:** Descriptive names for variables, functions, and classes improve code readability for yourself and others.
*   **Avoid hardcoding values:** Use configuration files, environment variables, or function parameters for values that might change, making your code more flexible.
*   **Write unit tests:** Tests verify that individual components of your code work as expected, catching bugs early and facilitating refactoring.

### Example
Here’s an example demonstrating how to break down a data transformation task into smaller, testable functions:
```python
def clean_data(record):
    return record.strip().lower()

def transform_data(records):
    return [clean_data(r) for r in records]
```
**Explanation:** The `clean_data` function handles a single record, making it easy to test in isolation. The `transform_data` function then applies this cleaning to a collection of records, demonstrating modularity.

## 9. Working with File Formats
Data engineers frequently work with various file formats. This section covers common formats and how to interact with them using Python.

### CSV (Comma-Separated Values)
CSV is a common plain-text format for tabular data. Python's built-in `csv` module is highly effective for reading and writing CSV files.
```python
import csv

# Example of reading a CSV file
# Assuming 'data.csv' exists with some data
# with open('data.csv') as f:
#     reader = csv.reader(f)
#     for row in reader:
#         print(row)
```

### JSON (JavaScript Object Notation)
JSON is a lightweight data-interchange format, often used for data transmission between a server and web application, or for configuration files. Python's `json` module allows easy serialization and deserialization of JSON data.
```python
import json

# Example of reading a JSON file
# Assuming 'data.json' exists with JSON formatted data
# with open('data.json') as f:
#     data = json.load(f)
#     print(data)
```


### Quiz Time!
1. Which Python library is commonly used for working with Parquet files?
   a) `csv`
   b) `json`
   c) `pandas`
   d) `fastavro`
   *Answer: c)*

2. If you need to read an Avro file, which library would you typically use?
   a) `pandas`
   b) `fastavro`
   c) `openpyxl`
   d) `sqlalchemy`
   *Answer: b)*

## 10. Error Handling and Logging
Robust data engineering pipelines require proper error handling and logging to ensure reliability and facilitate debugging. This section introduces basic techniques.

### Error Handling
Using `try-except` blocks allows your program to gracefully handle runtime errors, preventing crashes and providing informative feedback.
```python
try:
    value = int("abc") # This will raise a ValueError
except ValueError as e:
    print("Conversion failed:", e)
```
**Explanation:** The code inside the `try` block is executed. If a `ValueError` occurs (as when trying to convert "abc" to an integer), the code in the `except ValueError as e:` block is executed, printing a user-friendly message and the error details.

### Logging
Logging is crucial for tracking the execution flow of your applications, diagnosing issues, and monitoring system health. Python's `logging` module is powerful and flexible.
```python
import logging

# Configure basic logging to output to console with INFO level and above
logging.basicConfig(level=logging.INFO)

logging.info("Pipeline started")
# ... some processing ...
logging.error("An error occurred")
```
**Explanation:** `logging.basicConfig` sets up the basic configuration. `logging.info()` records informational messages, while `logging.error()` records error messages. These messages can include timestamps, module names, and other useful context.

### Quiz Time!
1. What keyword is used to handle potential errors in Python?
   a) `catch`
   b) `handle`
   c) `try`
   d) `error`
   *Answer: c)*

2. Which `logging` level is typically used to confirm that things are working as expected?
   a) INFO
   b) WARNING
   c) ERROR
   d) DEBUG
   *Answer: a)*

## 11. Summary
By the end of this lesson, students should:
*   Understand key data roles and systems
*   Know how data flows through a lifecycle
*   Be comfortable with Python basics
*   Handle different data formats
*   Write clean, modular, and reliable code

This summary reiterates the key learning objectives covered throughout the entire lesson program, emphasizing the comprehensive skills gained in Python for Data Engineering.

## 12. Suggested Exercises
Here's a suggested exercise based on the document content:

### Exercise: Read CSV and Convert to JSON
**Task:** Write Python code that reads data from a CSV file and converts it into a JSON file.
**Steps:**
1. Create a dummy CSV file named `sample_data.csv` with some data (e.g., `name,age\nAlice,30\nBob,24`).
2. Read the content of `sample_data.csv`.
3. Convert the CSV data into a list of dictionaries.
4. Write this list of dictionaries to a new JSON file named `sample_data.json`.

**Hint:** You can use the `csv` and `json` modules, as discussed in Point 9.